# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-08 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupvote',
            name='vote_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
