--UPDATE public.app_customuser
	--SET username=?, email=?, password=?, first_name=?, last_name=?, id=?, last_login=?, is_superuser=?, is_staff=?, is_active=?, date_joined=?
	--WHERE <condition>;
--ALTER TABLE app_customuser
--ALTER COLUMN username TYPE VARCHAR,
--ALTER COLUMN email TYPE VARCHAR,
--ALTER COLUMN password TYPE VARCHAR,
--ALTER COLUMN first_name TYPE VARCHAR,
--ALTER COLUMN last_name TYPE VARCHAR